apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  name: argo-workflow-step
spec:
  entrypoint: main
  templates:
    - name: main
      steps:
        - - name: step1
            template: echo-message
            arguments:
              parameters: [{ name: "message", value: "step1" }]
        - - name: step2
            template: echo-message
            arguments:
              parameters: [{ name: "message", value: "step2" }]
        - - name: step3
            template: echo-message
            arguments:
              parameters: [{ name: "message", value: "step3" }]
        - - name: step4
            template: echo-message
            arguments:
              parameters: [{ name: "message", value: "step4" }]
        - - name: step5
            template: echo-message
            arguments:
              parameters: [{ name: "message", value: "step5" }]

    - name: echo-message
      inputs:
        parameters:
          - name: message
      coniner:
        image: alpine
        command: ["echo", "{{inputs.parameters.message}}"]
