apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  name: argo-workflow-step
spec:
  entrypoint: main
  templates:
    - name: main
      steps:
        - - name: step1
            template: sleep-seconds
            arguments:
              parameters: 3
        - - name: step2
            template: sleep-seconds
            arguments:
              parameters: 5
        - - name: step3
            template: sleep-seconds
            arguments:
              parameters: 10
        - - name: step4
            template: sleep-seconds
            arguments:
              parameters: 15
        - - name: step5
            template: sleep-seconds
            arguments:
              parameters: 20

    - name: sleep-seconds
      inputs:
        parameters:
          - name: duration
      container:
        image: alpine
        command: ["sh", "-c"]
        args:
          - |
            sleep "{{inputs.parameters.duration}}"
