apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  name: argo-workflow-step
spec:
  entrypoint: main
  templates:
    - name: main
      steps:
        - - name: step1
            template: sleep-seconds
            arguments:
              parameters: [{ name: "duration", value: 3 }]
        - - name: step2
            template: sleep-seconds
            arguments:
              parameters: [{ name: "duration", value: 5 }]
        - - name: step3
            template: sleep-seconds
            arguments:
              parameters: [{ name: "duration", value: 10 }]
        - - name: step4
            template: sleep-seconds
            arguments:
              parameters: [{ name: "duration", value: 15 }]
        - - name: step5
            template: sleep-seconds
            arguments:
              parameters: [{ name: "duration", value: 20 }]

    - name: sleep-seconds
      inputs:
        parameters:
          - name: duration
      container:
        image: alpine
        command: ["sh", "-c"]
        args: ["sleep {{inputs.parameters.duration}}"]
