apiVersion: getambassador.io/v2
kind: Module
metadata:
  name: ambassador
  namespace: ambassador
spec:
  config:
    cluster_request_timeout_ms: 60000
    envoy_log_type: json
    envoy_log_format:
      start_time: "%START_TIME%"
      method: "%REQ(:METHOD)%"
      path: "%REQ(X-ENVOY-ORIGINAL-PATH?:PATH)%"
      referer: "%REQ(REFERER)%"
      protocol: "%PROTOCOL%"
      response_code: "%RESPONSE_CODE%"
      response_flags: "%RESPONSE_FLAGS%"
      bytes_received: "%BYTES_RECEIVED%"
      bytes_sent: "%BYTES_SENT%"
      duration: "%DURATION%"
      upstream_service_time: "%RESP(X-ENVOY-UPSTREAM-SERVICE-TIME)%"
      x_forwarded_for: "%REQ(X-FORWARDED-FOR)%"
      user_agent: "%REQ(USER-AGENT)%"
      request_id: "%REQ(X-REQUEST-ID)%"
      authority: "%REQ(:AUTHORITY)%"
      upstream_host: "%UPSTREAM_HOST%"
      upstream_cluster: "%UPSTREAM_CLUSTER%"
      upstream_local_address: "%UPSTREAM_LOCAL_ADDRESS%"
      downstream_local_address: "%DOWNSTREAM_LOCAL_ADDRESS%"
      downstream_remote_address: "%DOWNSTREAM_REMOTE_ADDRESS%"
      requested_server_name: "%REQUESTED_SERVER_NAME%"
      istio_policy_status: "%DYNAMIC_METADATA(istio.mixer:status)%"
      upstream_transport_failure_reason: "%UPSTREAM_TRANSPORT_FAILURE_REASON%"
      request_origin_network: "%REQ(X-REQUEST-ORIGIN-NETWORK)%"
