apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: backend-app-1
spec:
  project: default
  destination:
    namespace: backend-app-1
    server: https://kubernetes.default.svc
  source:
    repoURL: https://github.com/takuyawww/k8s-manifest-sample
    targetRevision: main
    path: "backend-app-1/overlays/stg"
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
