# TODO: prd構築時に共通化できるものがあれば共通化する

apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-app-1-deployment
  labels:
    app: backend-app-1
spec:
  replicas: 3
  selector:
    matchLabels:
      app: backend-app-1
  template:
    metadata:
      labels:
        app: backend-app-1
    spec:
      containers:
        - name: backend-app-1
          image: k8s-sample-backend-app-1:v0.0.2
          imagePullPolicy: Never # ローカルのimageを取得する
          ports:
            - containerPort: 8081
