apiVersion: batch/v1
kind: Job
metadata:
  name: backend-app-1-pre-sync-job
  annotations:
    argocd.argoproj.io/hook: PreSync
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
spec:
  completions: 3
  parallelism: 2
  template:
    spec:
      containers:
        - name: sleep
          image: alpine
          command: ["sh", "-c"]
          args:
            - |
              sleep 60
      restartPolicy: Never
