# TODO: prd構築時に共通化できるものがあれば共通化する

apiVersion: v1
kind: Service
metadata:
  name: backend-app-1-service
spec:
  selector:
    app: backend-app-1
  type: NodePort
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8081
      name: http
